### ISSUE TITLE
Fails with multiple connected cameras

### ISSUE THREAD

**Issue by FreedCapybara** [Huddly/device-api-usb#101]
Hi,

I get the following error when trying to run the basic people counting example when there are multiple cameras attached:

2019-10-14 | 14:12:56:698 | DEBUG | Device API USB Manager | Got ATTACH event from device with id 10005
2019-10-14 | 14:12:56:702 | DEBUG | Device API USB Manager | Got ATTACH event from device with id 10008
2019-10-14 | 14:12:56:962 | DEBUG | Device API USB Manager | DeviceList found 2 enumerated Huddly devices
2019-10-14 | 14:12:56:963 | DEBUG | Device API USB Manager | Filtering the devices for the following serial number: B41A00826
2019-10-14 | 14:12:56:966 | INFO | Device API USB | Transport Protocol is Hlink
2019-10-14 | 14:12:56:968 | DEBUG | Autozoom Control | Initializing autozoom with framing config option AUTO_PTZ: true
2019-10-14 | 14:12:56:969 | DEBUG | Autozoom Control | Uploading new framing config
2019-10-14 | 14:12:57:172 | DEBUG | Autozoom Control | New framing config uploaded on the camera.
2019-10-14 | 14:12:57:288 | DEBUG | Device API USB Manager | DeviceList found 2 enumerated Huddly devices
2019-10-14 | 14:12:57:289 | DEBUG | Device API USB Manager | Filtering the devices for the following serial number: B41B01163
2019-10-14 | 14:12:57:290 | ERROR | Device API USB Transport | Failed in bulk read write! Resuming.
Error: Unknown error -100
    at Object.errstr (C:\MAIA\MAIA-experience\camera-analytics\node_modules\@huddly\device-api-usb\src\errstr.ts:32:14)
    at _cpp.readDevice.ret (C:\MAIA\MAIA-experience\camera-analytics\node_modules\@huddly\device-api-usb\src\bulkusbendpoint.ts:44:31)
2019-10-14 | 14:12:57:306 | INFO | Device API USB | Transport Protocol is Hlink
2019-10-14 | 14:12:57:407 | ERROR | Device API USB Transport | Failed in bulk read write! Resuming.
Error: Unknown error -100
    at Object.errstr (C:\MAIA\MAIA-experience\camera-analytics\node_modules\@huddly\device-api-usb\src\errstr.ts:32:14)
    at _cpp.readDevice.ret (C:\MAIA\MAIA-experience\camera-analytics\node_modules\@huddly\device-api-usb\src\bulkusbendpoint.ts:44:31)
2019-10-14 | 14:12:57:510 | ERROR | Device API USB Transport | Failed in bulk read write! Resuming.
Error: Unknown error -100
    at Object.errstr (C:\MAIA\MAIA-experience\camera-analytics\node_modules\@huddly\device-api-usb\src\errstr.ts:32:14)
    at _cpp.readDevice.ret (C:\MAIA\MAIA-experience\camera-analytics\node_modules\@huddly\device-api-usb\src\bulkusbendpoint.ts:44:31)

**Comment by jontore** [comment]
Right now multiple cameras are not supported at the moment. Could you explain the use case for it, it something that would be possible to add support for, but until now not been necessary.

**Comment by FreedCapybara** [comment]
We have a primary Huddly camera as the main video feed for a meeting room as well as people detections, and a secondary Huddly camera pointed at a whiteboard. We'd like to have detections work on the primary camera and still have the ability to use the secondary camera, but we're having the issue as described above.

If it's too much effort to support multiple cameras, it would be great if we could pick one during setup (maybe by serial number, or even an integer) and have the script not fail.

**Comment by brikendr** [comment]
@FreedCapybara I'll have a look and see how we can tackle the problem you are facing. I will update you as soon as we have a fix for this.

**Comment by brikendr** [comment]
@FreedCapybara First of all we are sorry for the confusion in our side, but SDK supports targeting a specific camera while having multiple Huddly cameras connected to your host machine.

What we do not support is:

- Communicating with multiple cameras at the same time on a single node process
- Targeting the same camera from two different node process (ex. running the same application from two different terminal while still targeting the same camera serial)

As such, in your case where you have two different Huddly IQ cameras connected on the same host machine, you must tell the SDK which camera you are going to use in your appication that is consuming the SDK (by using the serial number of course). When initializing the SDK, it is possible to specify the target serial number in the options argument. The code below demonstrates how to do just that:

```javascript
const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;

const meetingRoomName = process.env.HUDDLY_MEETING_ROOM || 'TEST_ROOM';
const cameraSerialNumber = process.env.DETECTIONS_SERIAL_NUMBER || 'B41A00826';

const usbApi = new HuddlyDeviceAPIUSB();

// Create an instance of the SDK
const sdk = new HuddlySdk(usbApi, [usbApi], {
  serial: cameraSerialNumber, // Target a specific camera using serial number
});

sdk.on('ATTACH', async (cameraManager) => {
  const autozoomCtl = cameraManager.getAutozoomControl();
  // Make sure that autozoom (genius framing is started)
  await autozoomCtl.init();
  await autozoomCtl.start();

  // Detector options to get head and person detections without streaming main
  const detectorOpts = {
    // DOWS: false, // DOWS is default false!
    objectFilter: ['head', 'person']
  };

  const detector = cameraManager.getDetector(detectorOpts);

  // Setup the detection listener
  detector.on('DETECTIONS', detections => {
    // detection stuff
    console.log(`Got ${detections.length} detections from camera with serial ${cameraManager.serialNumber}`)
  });

  // Calling detector init will initiate the generation of detection events
  detector.init();

  process.on('SIGINT', async () => {
    console.log("\nClosing application gracefully");
    if (detector) {
      console.log('Destroying detector');
      await detector.destroy();
    }

    if (cameraManager) {
      console.log('Closing connection with the camera');
      await cameraManager.closeConnection();
    }
    console.log("\nTeardown completed! Application closed");
    process.exit();
  });
});

sdk.init();
```

Please try the example above and let us know if you experience any issues with it.

P.S I tried the code snipped above while having two Huddly IQ cameras connected on my machine and no failures were observed.

**Comment by FreedCapybara** [comment]
Thank you, I believe I am within the supported use-case, and adding the serial number during SDK setup does fix the issue 👍 

One thing to note: both my code and the code you posted doesn't work if you have the Huddly App running. The program logs an ATTACH event and appears to hang (might not actually hang, but it doesn't log any further output).
